version: '3.7'

services:
  django:
    build:
      dockerfile: ./docker/Dockerfile.prod
    expose:
      - 8001
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      # 443:443
    volumes:
      - ./docker/nginx-observ.conf:/etc/nginx/conf.d/nginx-observ.conf:ro
     #- ../tree-volumes/static:/tree-volumes/static
     #- ../tree-volumes/media:/tree-volumes/media
     #- ../tree-volumes/certbot/conf:/etc/letsencrypt
     #- ../tree-volumes/certbot/www:/var/www/certbot
