version: '3.7'

networks:
  gateway:
    external: true
  internal:
    external: false

services:
  django:
    labels:
      - traefik.enable=true
      #- traefik.docker.network=observ_default
      - traefik.http.routers.observ.entrypoints=web
      - traefik.http.routers.observ.rule=Host(`my-observ.mg`)
      - traefik.http.services.observ.loadbalancer.server.port=8001
    #ports:
    #  - 80:8001
    expose:
      - 8001
    networks:
      - internal
      - gateway

  postgres:
    networks:
      - internal