version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PYTHON_VERSION: ${ARG_PYTHON_VERSION}
    container_name: po-django-${WEB_ENV}-container
    image: po-django-${WEB_ENV}-image
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../observ-volumes/static:/observ-volumes/static
      - ../observ-volumes/media:/observ-volumes/media
      #- ../ct22-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    #env_file: not working
    #  - ./docker/.env.dev
    environment:
      - WEB_ENV=${WEB_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  postgres:
    image: postgres:14-alpine
    container_name: po-postgres-container
    restart: always
    volumes:
      - ../observ-volumes/pgdata:/var/lib/postgresql/data/pgdata
      #- ../po-volumes/bucket:/bucket
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata