version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: ./docker-scripts/Dockerfile-prod
    container_name: po-django-prod-container
    image: po-django-prod-image
    expose:
      - 8001
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../observ-volumes/static:/ct22-volumes/static
      - ../observ-volumes/media:/ct22-volumes/media
      #- ../ct22-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    environment:
      - WEB_ENV=prod
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=observ

  postgres:
    image: postgres:14-alpine
    container_name: po-postgres-container
    restart: always
    volumes:
      - ../observ-volumes/pgdata:/var/lib/postgresql/data/pgdata
      #- ../po-volumes/bucket:/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=observ
      - PGDATA=/var/lib/postgresql/data/pgdata

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
     - ./docker-scripts/nginx-observ.conf:/etc/nginx/conf.d/nginx-observ.conf:ro
     #- ../tree-volumes/static:/tree-volumes/static
     #- ../tree-volumes/media:/tree-volumes/media
     #- ../tree-volumes/certbot/conf:/etc/letsencrypt
     #- ../tree-volumes/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 90:90
    # - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"