# Generated by Django 4.0.5 on 2022-06-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '物種',
                'verbose_name_plural': '物種',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '地點', 'verbose_name_plural': '地點'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人員', 'verbose_name_plural': '人員 '},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '計劃', 'verbose_name_plural': '計劃'},
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.species')),
            ],
            options={
                'verbose_name': '植物編號',
                'verbose_name_plural': '植物編號',
            },
        ),
    ]
