# Generated by Django 4.0.5 on 2022-06-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_species_alter_location_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
