# Generated by Django 4.0.5 on 2022-06-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementorfactparameter',
            options={'verbose_name': '紀錄參數', 'verbose_name_plural': '紀錄參數'},
        ),
        migrations.AlterModelOptions(
            name='measurementorfactparametercategory',
            options={'verbose_name': '紀錄參數分類', 'verbose_name_plural': '紀錄參數分類'},
        ),
        migrations.AddField(
            model_name='measurementorfactparameter',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.measurementorfactparametercategory'),
        ),
    ]
