# Generated by Django 4.0.5 on 2022-06-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_measurementorfactparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '調查活動', 'verbose_name_plural': '調查活動'},
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(to='app.person', verbose_name='list of sites'),
        ),
    ]
