# Generated by Django 4.0.5 on 2022-06-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_options_event_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementorfactparametercategory',
            name='label',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='measurementorfactparametercategory',
            name='seq',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
