# Generated by Django 4.0.5 on 2022-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_measurementorfactparametercategory_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementorfact',
            options={'verbose_name': '紀錄內容', 'verbose_name_plural': '紀錄內容'},
        ),
        migrations.AlterModelOptions(
            name='measurementorfactparametercategory',
            options={'ordering': ['seq'], 'verbose_name': '紀錄參數分類', 'verbose_name_plural': '紀錄參數分類'},
        ),
        migrations.RemoveField(
            model_name='measurementorfact',
            name='name',
        ),
        migrations.AddField(
            model_name='measurementorfact',
            name='parameters',
            field=models.ManyToManyField(to='app.measurementorfactparameter', verbose_name='parameters'),
        ),
        migrations.AddField(
            model_name='measurementorfact',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
