# Generated by Django 4.0.5 on 2022-06-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_measurementorfact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementorfactparameter',
            options={'ordering': ['category__seq', 'seq'], 'verbose_name': '紀錄參數', 'verbose_name_plural': '紀錄參數'},
        ),
        migrations.AddField(
            model_name='measurementorfactparametercategory',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='label',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
