# Generated by Django 4.0.5 on 2022-06-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_location_event_principle_event_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementorfact',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event'),
        ),
        migrations.AddField(
            model_name='measurementorfact',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plant'),
        ),
    ]
