#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#npm run build-dev

#python manage.py migrate --delete-ghost-migrations
#python manage.py qcluster & python manage.py runserver 0.0.0.0:8000
#python manage.py runserver_plus 0.0.0.0:8000

if [ "$WEB_ENV" == "prod" ]; then
    python manage.py migrate --no-input
    python manage.py collectstatic --no-input
    gunicorn --bind 0.0.0.0:8001 --timeout 60 conf.wsgi #--chdir=/code
else
    python manage.py migrate
    python manage.py collectstatic --no-input
    python manage.py runserver 0.0.0.0:8000
fi
